name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

  workflow_call:
    inputs:
      ref_name:
        description: Tag short ref name like v1.2.3
        type: string
        required: true

concurrency:
  group: release
  cancel-in-progress: false

env:
  REGISTRY_USER: motoki317
  IMAGE: traq-webhook-converter

jobs:
  image:
    uses: ./.github/workflows/image.yaml
    with:
      ref_name: ${{ inputs.ref_name }}

  release:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' || inputs.ref_name != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          # tag_name will default in the current branch name for workflow_dispatch via workflow_call, so we're passing tag value via inputs manually.
          tag_name: ${{ inputs.ref_name || github.ref_name }}
          generate_release_notes: true
